apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
bases:
  # Default Stack installation - Step 1 (without env specific configuration)
  - ../../base

resources:
  # ArgoCD Cluster secrets to access remote k8s clusters
  # - resources/cluster-secrets

#  # ArgoCD Project onboarding
#  - https://github.com/catenax-ng/product-onboarding/cluster/beta
#  - https://github.com/catenax-ng/product-onboarding/cluster/dev
#  - https://github.com/catenax-ng/product-onboarding/cluster/devsecops-testing
#  - https://github.com/catenax-ng/product-onboarding/cluster/int
#  - https://github.com/catenax-ng/product-onboarding/cluster/pre-prod

  #

patchesStrategicMerge:
#  -
