apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Default Stack deployment
  - https://github.com/catenax-ng/k8s-cluster-stack/apps/argocd/base # will be replaced by next line
#  - https://github.com/catenax-ng/k8s-cluster-stack/v0.1.2/argo → kustomize # remote will be kustomize too
#  - https://github.com/catenax-ng/k8s-cluster-stack/v0.1.2/apps → Umbrella Chart # remote will be kustomize too

  # Additional deployment
  - resources/image-pull-secret.yaml
  - resources/storage-class.yaml
